import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';
const sidebars: SidebarsConfig = {
  guideSidebar: [{type: 'autogenerated', dirName: 'guide'}],
  learningSidebar: [{type: 'autogenerated', dirName: 'learning'}],
  fullDocsSidebar: [{type: 'autogenerated', dirName: 'catenary'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
